[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "semapapo"
version = "1.4.1"
description = "semapapo"
authors = [{ name = "potalej" }, { name = "jcgs" }, { name="yuri-pin"} ]
readme = "README.md"
dependencies = []

[project.scripts]
semapapo = "semapapo.semapapo:semapapo"
